# Generated by Django 6.1 on 2026-09-09 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('education_title', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('started_at_year', models.IntegerField(max_length=4)),
                ('ended_at_year', models.IntegerField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
