# Generated by Django 6.1 on 2026-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_edhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edhistory',
            name='ended_at_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edhistory',
            name='started_at_year',
            field=models.IntegerField(),
        ),
    ]
